const builder = require("./index")

const builder1 = new builder();
console.log("================")
console.log(builder1.select("specialities.speciality_id,specialities.name,specialities.slug")
                    .from("specialities")
                    .join('specialities_doctors','specialities_doctors.speciality_id = specialities.speciality_id')
                    .join('specialities_hospitals','specialities_hospitals.speciality_id = specialities.speciality_id')
                    .join('hospitals','hospitals.hospital_id = specialities_hospitals.hospital_id')
                    .join('doctors_indian_hospitals','doctors_indian_hospitals.doctor_id = specialities_doctors.doctor_id')
                    .join('speciality_indian_hospitals','speciality_indian_hospitals.speciality_id = specialities.speciality_id')
                    .join('indian_hospitals','indian_hospitals.hospital_id = speciality_indian_hospitals.indian_hospital_id')
                    .join('doctors_hospitals','doctors_hospitals.doctor_id = specialities_doctors.doctor_id')
                    .where('doctors_indian_hospitals.indian_hospital_id', '=' ,'speciality_indian_hospitals.indian_hospital_id')
                    .where('specialities_hospitals.hospital_id',"=",1)
                    .where('doctors_hospitals.hospital_id',"=",1)
                    .whereIn('specialities_doctors.doctor_id',[1,2,3,4,5,6])
                    .whereIn('doctors_hospitals.doctor_id',[12,23,14,54])
                    .where('hospitals.status_ind',"=", 1)
                    .where('doctors_hospitals.status_ind',"=", 1)
                    .where('specialities.status_ind',1)
                    .groupBy('specialities.speciality_id')
                    .get())
console.log("================")
//  console.log(builder1.getLastQuery())
